### ISSUE TITLE
So confusing documentation..

### ISSUE THREAD

**Issue by erikdemarco** [moota-co/moota-php-sdk#2]
In the docs the attribute structures for getMutation is like this:

```
(
            'asdasd',
            '2021-09-21',
            'Testing Note Mutation',
            '2000123',
            'CR'
)
```

But in the source the getMutation attribute structures is like this:

```
(
        public null|string $type = '',
        public null|string $bank = '',
        public null|string $amount = '',
        public null|string $description = '',
        public null|string $note = '',
        public null|string $date = '',
        public null|string $start_date = '',
        public null|string $end_date = '',
        public null|string $tag = '',
        public int $page = 1,
        public int $per_page = 20,
)
```

Please give more docs example. Do we need to login and logout every single time we request an api?
It will be wasting our server resources to call moota's server multiple time. Its much more easier in v1 api, because its straight to the point no complicated stuff.

**Comment by erkurn** [comment]
Sorry for very slow response. we will improve and update the usage in the next version
